# Generated by Django 2.0.2 on 2018-03-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180303_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pub_date',
        ),
    ]
