# Generated by Django 2.0.2 on 2018-03-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_message_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='food',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='medicine',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='water',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
