# Generated by Django 2.0.2 on 2018-03-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20180303_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='blankets',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='power',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='toiletries',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
